import type { SiteCopy, Lang } from './types'
import { CONTACT } from '@/lib/contact'

export const COPY: Record<Lang, SiteCopy> = {
  pt: {
    sections: [
      { id: 'hero', label: 'hero', index: '01' },
      { id: 'projects', label: 'projetos', index: '02' },
      { id: 'about', label: 'sobre', index: '03' },
      { id: 'skills', label: 'skills', index: '04' },
      { id: 'contact', label: 'contato', index: '05' },
    ],
    hero: {
      tagline: '$ whoami',
      headlineLine1: 'Paulo Pierrondi',
      headlineLine2: '$ design_operate_scale_ai()',
      description:
        'Technical Account Executive na ServiceNow, arquiteto de IA e full-stack builder. Lidero contexto enterprise em FSI enquanto construo sistemas multi-agente, plataformas de automação e produtos digitais com trilha de evidência.',
      ctaPrimary: { label: 'ver projetos', href: '#projects' },
      ctaSecondary: { label: 'falar comigo', href: '#contact' },
      badges: [
        'AI/Automation Architect',
        'Full-stack Builder',
        'Technical Account Executive',
        'AgentOps',
      ],
    },
    projects: {
      heading: 'Projetos selecionados',
      items: [
        {
          id: 'agent-hub',
          status: { label: 'Em produção', live: true },
          number: '02.1',
          title: 'Agent Hub',
          subtitle: 'Automation OS · Multi-agent operations',
          description:
            'Sistema operacional para agentes: registry, scheduler, handoffs, memória, human gates e runners. Coordena coders, pesquisadores, validadores e operadores com papéis separados e entregas auditáveis.',
          tech: ['TypeScript', 'Next.js', 'Node', 'PostgreSQL', 'MCP', 'n8n'],
          stats: [
            { value: '24/7', label: 'automação' },
            { value: '60+', label: 'agentes registrados' },
            { value: '5', label: 'tipos de runner' },
          ],
          mockup: {
            kind: 'terminal',
            windowTitle: 'agent-hub',
            statusLine: '~/ops/agent-hub',
            lines: [
              { text: '$ agent-hub status', tone: 'prompt' },
              { text: 'registry: 62 agents | 5 runners | 12 pending', tone: 'output' },
              { text: 'scheduler: next_tick in 47s', tone: 'output' },
              { text: 'human-gates: 3 awaiting approval', tone: 'output' },
              { text: '---', tone: 'plain' },
              { text: 'orchestrator > plan #2026.07.10-a', tone: 'function' },
              { text: '  coder_claude    ● running  ~/worktrees/site-v2', tone: 'plain' },
              { text: '  qa_anthropic    ○ idle', tone: 'plain' },
              { text: '  validator_agy   ● running  smoke-test', tone: 'plain' },
              { text: '  release_guard   ○ waiting  human-gate', tone: 'plain' },
            ],
          },
          ctaPrimary: { label: 'ver detalhes', href: '/automacoes' },
        },
        {
          id: 'ai-control-tower',
          status: { label: 'Live', live: true },
          number: '02.2',
          title: 'AI Control Tower',
          subtitle: 'Operations dashboard · Agent governance',
          description:
            'Painel operacional que descobre, observa, governa e mede agentes, automações, worktrees e handoffs. Conecta missão, risco e próxima ação em um único comando.',
          tech: ['Next.js', 'React', 'PostgreSQL', 'ServiceNow MCP', 'IRM'],
          stats: [
            { value: '10', label: 'agentes especialistas' },
            { value: '100%', label: 'ações auditáveis' },
            { value: '90 dias', label: 'lighthouse FSO' },
          ],
          mockup: {
            kind: 'dashboard',
            windowTitle: 'control-tower',
            statusLine: '~/ops/control-tower',
            lines: [
              { text: 'AI Control Tower — FSI Brazil', tone: 'function' },
              { text: 'Mission: Card Dispute lighthouse', tone: 'plain' },
              { text: 'Risk state: GREEN | 0 high-blast actions', tone: 'output' },
              { text: 'Agents online: 10/10', tone: 'output' },
              { text: 'Automations today: 47', tone: 'output' },
              { text: 'Pending approvals: 3', tone: 'output' },
              { text: 'Last evidence pack: 2m ago', tone: 'output' },
              { text: 'Next review: 14:00 BRT', tone: 'output' },
            ],
          },
          ctaPrimary: { label: 'abrir painel', href: '/control_tower' },
        },
        {
          id: 'csdm-validator',
          status: { label: 'Live app', live: true },
          number: '02.3',
          title: 'CSDM / FSDM Validator',
          subtitle: 'ServiceNow data quality · FSO readiness',
          description:
            'Motor declarativo que avalia maturidade de CMDB/CSDM e conformidade FSDM, sugere correções com confiança ≥ 0.95 e mantém snapshot rollback. Base do plano automation-first FSO + IRM.',
          tech: ['Python', 'FastAPI', 'ServiceNow MCP', 'PostgreSQL', 'Pydantic'],
          stats: [
            { value: '≥ 85%', label: 'cobertura ATF' },
            { value: '0', label: 'orphan accounts' },
            { value: '40–55%', label: 'ciclo mais rápido' },
          ],
          mockup: {
            kind: 'code',
            windowTitle: 'csdm-validator',
            statusLine: '~/validators/csdm',
            lines: [
              { text: 'from validator import CsdmRuleSet, FsdmConformance', tone: 'keyword' },
              { text: '', tone: 'plain' },
              { text: 'rules = CsdmRuleSet.load("fsdm/card_dispute.json")', tone: 'plain' },
              { text: 'result = rules.evaluate(instance="bradesco-prod")', tone: 'function' },
              { text: '', tone: 'plain' },
              { text: 'assert result.maturity >= 0.85', tone: 'keyword' },
              { text: 'assert result.orphan_accounts == 0', tone: 'keyword' },
              { text: 'if result.blocking:', tone: 'keyword' },
              { text: '    raise ValidationError(result.blocking)', tone: 'function' },
              { text: '', tone: 'plain' },
              { text: '// snapshot rollback kept for 24h', tone: 'comment' },
            ],
          },
          ctaPrimary: { label: 'app ao vivo', href: 'https://csdm-validator-production.up.railway.app' },
        },
        {
          id: 'pierrondi-dev-platform',
          status: { label: 'Em produção', live: true },
          number: '02.4',
          title: 'pierrondi.dev',
          subtitle: 'Portfolio + AI search hub · GEO/SEO automation',
          description:
            'Site próprio, hub de busca com answer-docs, grafo de produtos e automação GEO/SEO. Gera páginas, citações e llms.txt para FaithSchool, CantuStudio e AgenticosCore.',
          tech: ['Next.js', 'TypeScript', 'Vercel', 'Node', 'LLMs.txt', 'answers.json'],
          stats: [
            { value: '3', label: 'produtos no grafo' },
            { value: '20+', label: 'answer docs' },
            { value: '2026', label: 'search-ready' },
          ],
          mockup: {
            kind: 'terminal',
            windowTitle: 'pierrondi.dev',
            statusLine: '~/site/pierrondi.dev',
            lines: [
              { text: '$ npm run build:answers', tone: 'prompt' },
              { text: '✓ answers.json              20 docs', tone: 'output' },
              { text: '✓ llms.txt                  3 products', tone: 'output' },
              { text: '✓ citations                 9 targets', tone: 'output' },
              { text: '✓ sitemap                   indexed', tone: 'output' },
              { text: '---', tone: 'plain' },
              { text: '$ npm run geo:sync', tone: 'prompt' },
              { text: '✓ faithschool.app           EN/PT', tone: 'output' },
              { text: '✓ cantustudio.app           EN/PT', tone: 'output' },
              { text: '✓ agenticoscore.ai          PT', tone: 'output' },
            ],
          },
          ctaPrimary: { label: 'explorar', href: '/ai-search' },
        },
        {
          id: 'sada',
          status: { label: 'Framework', live: true },
          number: '02.5',
          title: 'SADA',
          subtitle: 'Enterprise AI operating-model framework',
          description:
            'Linguagem de arquitetura prescritiva para conectar estratégia, decisões de arquitetura, execução em workflow e valor mensurável em implementações ServiceNow.',
          tech: ['ServiceNow', 'CSDM', 'Now Assist', 'AI Agents', 'IRM'],
          stats: [
            { value: '5', label: 'estágios do modelo' },
            { value: '4', label: 'pilares de atuação' },
            { value: 'FSI', label: 'foco regulado' },
          ],
          mockup: {
            kind: 'code',
            windowTitle: 'sada-framework',
            statusLine: '~/frameworks/sada',
            lines: [
              { text: 'const sada = new OperatingModel({', tone: 'keyword' },
              { text: '  stages: [', tone: 'plain' },
              { text: '    "intent", "context", "control",', tone: 'string' },
              { text: '    "action", "evidence"', tone: 'string' },
              { text: '  ],', tone: 'plain' },
              { text: '  pillars: [', tone: 'plain' },
              { text: '    "strategy", "platform",', tone: 'string' },
              { text: '    "agentops", "leadership"', tone: 'string' },
              { text: '  ],', tone: 'plain' },
              { text: '  sector: "FSI"', tone: 'plain' },
              { text: '})', tone: 'plain' },
              { text: '', tone: 'plain' },
              { text: 'sada.connect(ServiceNow).measureValue()', tone: 'function' },
            ],
          },
          ctaPrimary: { label: 'ver framework', href: '/feitos/sada-servicenow' },
        },
        {
          id: 'cantustudio',
          status: { label: 'Live app', live: true },
          number: '02.6',
          title: 'CantuStudio',
          subtitle: 'Produto de IA · SATB arranger app',
          description:
            'Aplicação que transforma melodias em arranjos SATB para coral, com backend de IA, validação musical, playback e exportação MusicXML. Prova pública de produto de IA com backend, app e exportação.',
          tech: ['TypeScript', 'Next.js', 'Python', 'MusicXML', 'AI/LLM'],
          stats: [
            { value: '4', label: 'vozes SATB' },
            { value: 'MusicXML', label: 'exportação' },
            { value: 'PT/EN', label: 'suporte' },
          ],
          mockup: {
            kind: 'dashboard',
            windowTitle: 'cantustudio',
            statusLine: '~/apps/cantustudio',
            lines: [
              { text: 'CantuStudio — SATB Arranger', tone: 'function' },
              { text: 'Input: melody (C major)', tone: 'plain' },
              { text: 'Voices: Soprano | Alto | Tenor | Bass', tone: 'output' },
              { text: 'Harmonization: complete', tone: 'output' },
              { text: 'Playback: ready', tone: 'output' },
              { text: 'Export: MusicXML', tone: 'output' },
              { text: 'Confidence: 0.94', tone: 'output' },
              { text: 'Status: awaiting human review', tone: 'output' },
            ],
          },
          ctaPrimary: { label: 'abrir app', href: 'https://cantustudio.app/gerar-arranjo-satb' },
        },
      ],
    },
    about: {
      heading: 'Sobre',
      bio: [
        'Sou carioca, vivi anos em Dublin e opero de São Paulo. Construí a carreira na interseção entre o que a tecnologia promete e o que a operação aguenta — é ali que IA enterprise vira valor ou vira risco.',
        'Hoje sou Technical Account Executive / Enterprise Architect na ServiceNow, focado em serviços financeiros. Meu trabalho não é vender "usar IA": é desenhar como a IA entra em trabalho real, com contexto, política, permissões, memória, validação, custo e evidência.',
        'Para sustentar isso, construo sistemas — frameworks de arquitetura de valor, AgentOps governados, pipelines de inferência e produtos digitais. Método antes da ferramenta; trilha de evidência antes da escala.',
      ],
      stats: [
        { value: 'FSI', label: 'foco em serviços financeiros regulados' },
        { value: '60+', label: 'agentes registrados no Agent Hub' },
        { value: '21', label: 'apps publicados na App Store' },
        { value: '5', label: 'estágios do operating model' },
      ],
      testimonials: [],
    },
    skills: {
      heading: 'Stack',
      intro:
        'A mesma disciplina opera contas enterprise e constrói produtos: arquitetura de IA, engenharia full-stack, automação de plataformas e liderança executiva.',
      categories: [
        {
          title: 'AI & Agents',
          icon: 'BrainCircuit',
          skills: [
            { name: 'Multi-agent orchestration', note: 'registry · handoffs' },
            { name: 'LLMOps' },
            { name: 'RAG' },
            { name: 'MCP / A2A' },
            { name: 'Claude · GPT · Gemini' },
            { name: 'Eval harnesses' },
            { name: 'Human gates' },
          ],
        },
        {
          title: 'Full-stack Engineering',
          icon: 'Terminal',
          skills: [
            { name: 'TypeScript' },
            { name: 'Next.js / React' },
            { name: 'Node' },
            { name: 'Python' },
            { name: 'Swift / iOS' },
            { name: 'PostgreSQL' },
            { name: 'FastAPI' },
          ],
        },
        {
          title: 'Automation & Platforms',
          icon: 'Workflow',
          skills: [
            { name: 'ServiceNow' },
            { name: 'Fluent SDK' },
            { name: 'Action Fabric' },
            { name: 'CI/CD' },
            { name: 'n8n-style pipelines' },
            { name: 'Observability' },
          ],
        },
        {
          title: 'Enterprise & Leadership',
          icon: 'Landmark',
          skills: [
            { name: 'Account direction' },
            { name: 'AI operating models' },
            { name: 'Governance' },
            { name: 'FSI' },
            { name: 'CSDM / CMDB' },
            { name: 'Value architecture' },
          ],
        },
      ],
    },
    contact: {
      heading: 'Contato',
      intro:
        'Vamos conversar sobre IA enterprise, arquitetura de agentes, modelos operacionais ou produtos digitais. Resposta por email, sem nomes de clientes.',
      email: CONTACT.email,
      form: {
        nameLabel: 'Nome',
        namePlaceholder: 'Seu nome',
        emailLabel: 'Email',
        emailPlaceholder: 'voce@empresa.com',
        messageLabel: 'Mensagem',
        messagePlaceholder: 'Sobre o que quer conversar?',
        submitLabel: 'Enviar mensagem',
        successMessage: 'Mensagem enviada. Respondo por email em breve.',
        errorMessage: 'Algo deu errado. Tente novamente ou envie um email direto.',
      },
      links: [
        { label: 'LinkedIn', href: CONTACT.linkedin },
        { label: 'GitHub', href: CONTACT.github },
      ],
      footer: {
        line: '© 2026 Paulo Pierrondi — built with Next.js + TypeScript',
        nav: [
          { label: 'blog', href: '/blog' },
          { label: 'portfolio', href: '/portfolio' },
          { label: 'sobre', href: '/about' },
          { label: 'contato', href: '/contato' },
        ],
      },
    },
  },
  en: {
    sections: [
      { id: 'hero', label: 'hero', index: '01' },
      { id: 'projects', label: 'projects', index: '02' },
      { id: 'about', label: 'about', index: '03' },
      { id: 'skills', label: 'skills', index: '04' },
      { id: 'contact', label: 'contact', index: '05' },
    ],
    hero: {
      tagline: '$ whoami',
      headlineLine1: 'Paulo Pierrondi',
      headlineLine2: '$ design_operate_scale_ai()',
      description:
        'Technical Account Executive at ServiceNow, AI architect and full-stack builder. I lead enterprise FSI context while building multi-agent systems, automation platforms and digital products with evidence trails.',
      ctaPrimary: { label: 'view projects', href: '#projects' },
      ctaSecondary: { label: 'get in touch', href: '#contact' },
      badges: [
        'AI/Automation Architect',
        'Full-stack Builder',
        'Technical Account Executive',
        'AgentOps',
      ],
    },
    projects: {
      heading: 'Selected projects',
      items: [
        {
          id: 'agent-hub',
          status: { label: 'In production', live: true },
          number: '02.1',
          title: 'Agent Hub',
          subtitle: 'Automation OS · Multi-agent operations',
          description:
            'An operating system for agents: registry, scheduler, handoffs, memory, human gates, and runners. Coordinates coders, researchers, validators, and operators with separated roles and auditable deliveries.',
          tech: ['TypeScript', 'Next.js', 'Node', 'PostgreSQL', 'MCP', 'n8n'],
          stats: [
            { value: '24/7', label: 'automation' },
            { value: '60+', label: 'registered agents' },
            { value: '5', label: 'runner types' },
          ],
          mockup: {
            kind: 'terminal',
            windowTitle: 'agent-hub',
            statusLine: '~/ops/agent-hub',
            lines: [
              { text: '$ agent-hub status', tone: 'prompt' },
              { text: 'registry: 62 agents | 5 runners | 12 pending', tone: 'output' },
              { text: 'scheduler: next_tick in 47s', tone: 'output' },
              { text: 'human-gates: 3 awaiting approval', tone: 'output' },
              { text: '---', tone: 'plain' },
              { text: 'orchestrator > plan #2026.07.10-a', tone: 'function' },
              { text: '  coder_claude    ● running  ~/worktrees/site-v2', tone: 'plain' },
              { text: '  qa_anthropic    ○ idle', tone: 'plain' },
              { text: '  validator_agy   ● running  smoke-test', tone: 'plain' },
              { text: '  release_guard   ○ waiting  human-gate', tone: 'plain' },
            ],
          },
          ctaPrimary: { label: 'see details', href: '/automacoes' },
        },
        {
          id: 'ai-control-tower',
          status: { label: 'Live', live: true },
          number: '02.2',
          title: 'AI Control Tower',
          subtitle: 'Operations dashboard · Agent governance',
          description:
            'Operations dashboard that discovers, observes, governs, and measures agents, automations, worktrees, and handoffs. Connects mission, risk, and next action in one command layer.',
          tech: ['Next.js', 'React', 'PostgreSQL', 'ServiceNow MCP', 'IRM'],
          stats: [
            { value: '10', label: 'specialist agents' },
            { value: '100%', label: 'auditable actions' },
            { value: '90 days', label: 'FSO lighthouse' },
          ],
          mockup: {
            kind: 'dashboard',
            windowTitle: 'control-tower',
            statusLine: '~/ops/control-tower',
            lines: [
              { text: 'AI Control Tower — FSI Brazil', tone: 'function' },
              { text: 'Mission: Card Dispute lighthouse', tone: 'plain' },
              { text: 'Risk state: GREEN | 0 high-blast actions', tone: 'output' },
              { text: 'Agents online: 10/10', tone: 'output' },
              { text: 'Automations today: 47', tone: 'output' },
              { text: 'Pending approvals: 3', tone: 'output' },
              { text: 'Last evidence pack: 2m ago', tone: 'output' },
              { text: 'Next review: 14:00 BRT', tone: 'output' },
            ],
          },
          ctaPrimary: { label: 'open dashboard', href: '/control_tower' },
        },
        {
          id: 'csdm-validator',
          status: { label: 'Live app', live: true },
          number: '02.3',
          title: 'CSDM / FSDM Validator',
          subtitle: 'ServiceNow data quality · FSO readiness',
          description:
            'Declarative engine that scores CMDB/CSDM maturity and FSDM conformance, suggests fixes at ≥ 0.95 confidence, and keeps snapshot rollback. Foundation of the automation-first FSO + IRM plan.',
          tech: ['Python', 'FastAPI', 'ServiceNow MCP', 'PostgreSQL', 'Pydantic'],
          stats: [
            { value: '≥ 85%', label: 'ATF coverage' },
            { value: '0', label: 'orphan accounts' },
            { value: '40–55%', label: 'faster build cycle' },
          ],
          mockup: {
            kind: 'code',
            windowTitle: 'csdm-validator',
            statusLine: '~/validators/csdm',
            lines: [
              { text: 'from validator import CsdmRuleSet, FsdmConformance', tone: 'keyword' },
              { text: '', tone: 'plain' },
              { text: 'rules = CsdmRuleSet.load("fsdm/card_dispute.json")', tone: 'plain' },
              { text: 'result = rules.evaluate(instance="bradesco-prod")', tone: 'function' },
              { text: '', tone: 'plain' },
              { text: 'assert result.maturity >= 0.85', tone: 'keyword' },
              { text: 'assert result.orphan_accounts == 0', tone: 'keyword' },
              { text: 'if result.blocking:', tone: 'keyword' },
              { text: '    raise ValidationError(result.blocking)', tone: 'function' },
              { text: '', tone: 'plain' },
              { text: '// snapshot rollback kept for 24h', tone: 'comment' },
            ],
          },
          ctaPrimary: { label: 'live app', href: 'https://csdm-validator-production.up.railway.app' },
        },
        {
          id: 'pierrondi-dev-platform',
          status: { label: 'In production', live: true },
          number: '02.4',
          title: 'pierrondi.dev',
          subtitle: 'Portfolio + AI search hub · GEO/SEO automation',
          description:
            'Owned site and AI search hub with answer-docs, product graph, and GEO/SEO automation. Generates pages, citations, and llms.txt for FaithSchool, CantuStudio, and AgenticosCore.',
          tech: ['Next.js', 'TypeScript', 'Vercel', 'Node', 'LLMs.txt', 'answers.json'],
          stats: [
            { value: '3', label: 'products in graph' },
            { value: '20+', label: 'answer docs' },
            { value: '2026', label: 'search-ready' },
          ],
          mockup: {
            kind: 'terminal',
            windowTitle: 'pierrondi.dev',
            statusLine: '~/site/pierrondi.dev',
            lines: [
              { text: '$ npm run build:answers', tone: 'prompt' },
              { text: '✓ answers.json              20 docs', tone: 'output' },
              { text: '✓ llms.txt                  3 products', tone: 'output' },
              { text: '✓ citations                 9 targets', tone: 'output' },
              { text: '✓ sitemap                   indexed', tone: 'output' },
              { text: '---', tone: 'plain' },
              { text: '$ npm run geo:sync', tone: 'prompt' },
              { text: '✓ faithschool.app           EN/PT', tone: 'output' },
              { text: '✓ cantustudio.app           EN/PT', tone: 'output' },
              { text: '✓ agenticoscore.ai          PT', tone: 'output' },
            ],
          },
          ctaPrimary: { label: 'explore', href: '/ai-search' },
        },
        {
          id: 'sada',
          status: { label: 'Framework', live: true },
          number: '02.5',
          title: 'SADA',
          subtitle: 'Enterprise AI operating-model framework',
          description:
            'Prescriptive architecture language connecting strategy, architecture decisions, workflow execution, and measurable value in ServiceNow implementations.',
          tech: ['ServiceNow', 'CSDM', 'Now Assist', 'AI Agents', 'IRM'],
          stats: [
            { value: '5', label: 'model stages' },
            { value: '4', label: 'practice pillars' },
            { value: 'FSI', label: 'regulated focus' },
          ],
          mockup: {
            kind: 'code',
            windowTitle: 'sada-framework',
            statusLine: '~/frameworks/sada',
            lines: [
              { text: 'const sada = new OperatingModel({', tone: 'keyword' },
              { text: '  stages: [', tone: 'plain' },
              { text: '    "intent", "context", "control",', tone: 'string' },
              { text: '    "action", "evidence"', tone: 'string' },
              { text: '  ],', tone: 'plain' },
              { text: '  pillars: [', tone: 'plain' },
              { text: '    "strategy", "platform",', tone: 'string' },
              { text: '    "agentops", "leadership"', tone: 'string' },
              { text: '  ],', tone: 'plain' },
              { text: '  sector: "FSI"', tone: 'plain' },
              { text: '})', tone: 'plain' },
              { text: '', tone: 'plain' },
              { text: 'sada.connect(ServiceNow).measureValue()', tone: 'function' },
            ],
          },
          ctaPrimary: { label: 'see framework', href: '/feitos/sada-servicenow' },
        },
        {
          id: 'cantustudio',
          status: { label: 'Live app', live: true },
          number: '02.6',
          title: 'CantuStudio',
          subtitle: 'AI product · SATB arranger app',
          description:
            'Application that turns melodies into SATB choir arrangements, with AI backend, musical validation, playback, and MusicXML export. Public proof of an AI product with backend, app, and export.',
          tech: ['TypeScript', 'Next.js', 'Python', 'MusicXML', 'AI/LLM'],
          stats: [
            { value: '4', label: 'SATB voices' },
            { value: 'MusicXML', label: 'export' },
            { value: 'PT/EN', label: 'support' },
          ],
          mockup: {
            kind: 'dashboard',
            windowTitle: 'cantustudio',
            statusLine: '~/apps/cantustudio',
            lines: [
              { text: 'CantuStudio — SATB Arranger', tone: 'function' },
              { text: 'Input: melody (C major)', tone: 'plain' },
              { text: 'Voices: Soprano | Alto | Tenor | Bass', tone: 'output' },
              { text: 'Harmonization: complete', tone: 'output' },
              { text: 'Playback: ready', tone: 'output' },
              { text: 'Export: MusicXML', tone: 'output' },
              { text: 'Confidence: 0.94', tone: 'output' },
              { text: 'Status: awaiting human review', tone: 'output' },
            ],
          },
          ctaPrimary: { label: 'open app', href: 'https://cantustudio.app/gerar-arranjo-satb' },
        },
      ],
    },
    about: {
      heading: 'About',
      bio: [
        'I am from Rio, lived for years in Dublin, and operate from São Paulo. I built my career at the intersection of what technology promises and what operations can absorb — that is where enterprise AI becomes value or risk.',
        'Today I am a Technical Account Executive / Enterprise Architect at ServiceNow, focused on financial services. My job is not to sell "using AI": it is to design how AI enters real work, with context, policy, permissions, memory, validation, cost, and evidence.',
        'To sustain that, I build systems — value architecture frameworks, governed AgentOps, inference pipelines, and digital products. Method before tool; evidence trail before scale.',
      ],
      stats: [
        { value: 'FSI', label: 'focus on regulated financial services' },
        { value: '60+', label: 'agents registered in Agent Hub' },
        { value: '21', label: 'apps published on the App Store' },
        { value: '5', label: 'operating-model stages' },
      ],
      testimonials: [],
    },
    skills: {
      heading: 'Stack',
      intro:
        'The same discipline operates enterprise accounts and builds products: AI architecture, full-stack engineering, platform automation, and executive leadership.',
      categories: [
        {
          title: 'AI & Agents',
          icon: 'BrainCircuit',
          skills: [
            { name: 'Multi-agent orchestration', note: 'registry · handoffs' },
            { name: 'LLMOps' },
            { name: 'RAG' },
            { name: 'MCP / A2A' },
            { name: 'Claude · GPT · Gemini' },
            { name: 'Eval harnesses' },
            { name: 'Human gates' },
          ],
        },
        {
          title: 'Full-stack Engineering',
          icon: 'Terminal',
          skills: [
            { name: 'TypeScript' },
            { name: 'Next.js / React' },
            { name: 'Node' },
            { name: 'Python' },
            { name: 'Swift / iOS' },
            { name: 'PostgreSQL' },
            { name: 'FastAPI' },
          ],
        },
        {
          title: 'Automation & Platforms',
          icon: 'Workflow',
          skills: [
            { name: 'ServiceNow' },
            { name: 'Fluent SDK' },
            { name: 'Action Fabric' },
            { name: 'CI/CD' },
            { name: 'n8n-style pipelines' },
            { name: 'Observability' },
          ],
        },
        {
          title: 'Enterprise & Leadership',
          icon: 'Landmark',
          skills: [
            { name: 'Account direction' },
            { name: 'AI operating models' },
            { name: 'Governance' },
            { name: 'FSI' },
            { name: 'CSDM / CMDB' },
            { name: 'Value architecture' },
          ],
        },
      ],
    },
    contact: {
      heading: 'Contact',
      intro:
        "Let's talk about enterprise AI, agent architecture, operating models, or digital products. Reply by email, no client names.",
      email: CONTACT.email,
      form: {
        nameLabel: 'Name',
        namePlaceholder: 'Your name',
        emailLabel: 'Email',
        emailPlaceholder: 'you@company.com',
        messageLabel: 'Message',
        messagePlaceholder: 'What do you want to talk about?',
        submitLabel: 'Send message',
        successMessage: 'Message sent. I will reply by email soon.',
        errorMessage: 'Something went wrong. Please try again or send an email directly.',
      },
      links: [
        { label: 'LinkedIn', href: CONTACT.linkedin },
        { label: 'GitHub', href: CONTACT.github },
      ],
      footer: {
        line: '© 2026 Paulo Pierrondi — built with Next.js + TypeScript',
        nav: [
          { label: 'blog', href: '/blog' },
          { label: 'portfolio', href: '/portfolio' },
          { label: 'about', href: '/about' },
          { label: 'contact', href: '/contato' },
        ],
      },
    },
  },
}
